export const coffesAvaliable = [
  {
    id: '1',
    price: 9,
    amount: 1,
    description: 'O tradicional café feito com água quente e grãos moídos',
    type: 'Expresso Tradicional',
    status: ['Tradicional'],
    url: '/image1.png',
    inventory: 20,
  },
  {
    id: '2',
    price: 9,
    amount: 1,
    description: 'Expresso diluído, menos intenso que o tradicional',
    type: 'Expresso Americano',
    status: ['Tradicional'],
    url: '/image2.png',
    inventory: 20,
  },
  {
    id: '3',
    price: 9,
    amount: 1,
    description: 'Café expresso tradicional com espuma cremosa',
    type: 'Expresso Cremoso',
    status: ['Tradicional'],
    url: '/image3.png',
    inventory: 20,
  },
  {
    id: '4',
    price: 9,
    amount: 1,
    description: 'Bebida preparada com café expresso e cubos de gelo',
    type: 'Expresso Gelado',
    status: ['Tradicional', 'Gelado'],
    url: '/image4.png',
    inventory: 20,
  },
  {
    id: '5',
    price: 9,
    amount: 1,
    description: 'Meio a meio de expresso tradicional com leite vaporizado',
    type: 'Café com Leite',
    status: ['Tradicional', 'Com leite'],
    url: '/image5.png',
    inventory: 20,
  },
  {
    id: '6',
    price: 9,
    amount: 1,
    description:
      'Uma dose de café expresso com o dobro de leite e espuma cremosa',
    type: 'Latte',
    status: ['Tradicional', 'Com leite'],
    url: '/image6.png',
    inventory: 20,
  },
  {
    id: '7',
    price: 9,
    amount: 1,
    description:
      'Bebida com canela feita de doses iguais de café, leite e espuma',
    type: 'Capuccino',
    status: ['Tradicional', 'Com leite'],
    url: '/image7.png',
    inventory: 20,
  },
  {
    id: '8',
    price: 9,
    amount: 1,
    description:
      'Café expresso misturado com um pouco de leite quente e espuma',
    type: 'Macchiato',
    status: ['Tradicional', 'Com leite'],
    url: '/image8.png',
    inventory: 20,
  },
  {
    id: '9',
    price: 9,
    amount: 1,
    description: 'Café expresso com calda de chocolate, pouco leite e espuma',
    type: 'Mocaccino',
    status: ['Tradicional', 'Com leite'],
    url: '/image9.png',
    inventory: 20,
  },
  {
    id: '10',
    price: 9,
    amount: 1,
    description: 'Bebida feita com chocolate dissolvido no leite quente e café',
    type: 'Chocolate Quente',
    status: ['Especial', 'Com leite'],
    url: '/image10.png',
    inventory: 20,
  },
]
